name: Build Angular App

on:
  push:
    branches: [ main ]

jobs: 
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Node JS
        uses: actions/setup-node@v5.0.0 
        with: 
         node-version: 24.x

      - name: Install Dependencies
        run: npm install
        working-directory: ./myapp

      - name: Build
        run: npm run build
        working-directory: ./myapp
        
       

      
