name: Build and Test

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      run-tests:
        required: true
        type: boolean
    outputs:
      build-output-path:
        description: 'Path to build output folder'
        value: ${{ jobs.build.outputs.build-output-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-output-path: ${{ steps.set-build-output.outputs.build-folder }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Build
        id: build-step
        run: |
          # Simulate build, create build folder path output
          echo "build-output-folder=dist" >> $GITHUB_OUTPUT

      - name: Set build output
        id: set-build-output
        run: echo "::set-output name=build-folder::dist"
