name: Build Angular App

on:
  push:
    branches: [ main ]

jobs: 
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Node JS
        uses: actions/setup-node@v5.0.0 
        with: 
         node-version: 24.x

      - name: Install Dependencies
        run: npm install
        working-directory: ./myapp

      - name: Build
        run: npm run build
        working-directory: ./myapp

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.2
        with: 
         name: angular-dist
         path: ./myapp/dist

  deploy-angular:
    runs-on: ubuntu-latest    
    if: ${{ always() }}  
    needs:
        - build-angular
    steps: 
      - name: test
        run: echo "test step"
    
      
       

      
