name: Deploy Angular App

on:
  workflow_dispatch:
  

jobs: 
  deploy-angular:
    runs-on: ubuntu-latest    
    steps: 
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v11
        with: 
          name: build-artifact
          workflow: build-angular.yml
          path: artifact
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run_number: 9
      
      - name: Display structure of downloaded files
        run: ls -R artifact  
